[package]
name = "RAY_TRACER"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.24.0"
glam = "0.30.9"
glfw = "0.60.0"
glow = "0.13"
rand = "0.9.2"
random = "0.14.1"
winit = "0.30"
